In [1]:
#Assignment 4: Program to create arrays and add two matrices

In [7]:
import numpy as np 

matrix1 = np.array([
    [2,4],
    [8,6]
])

matrix2 = np.array([
    [3,9],
    [7,1]
])

result = matrix1 + matrix2

print("First Matrix")
print(matrix1)

print("\nSecond Matrix")
print(matrix2)

print("\nAddntion of two Matrices:")
print(result)

First Matrix
[[2 4]
 [8 6]]

Second Matrix
[[3 9]
 [7 1]]

Addntion of two Matrices:
[[ 5 13]
 [15  7]]
